name: CI

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: installing
        run: yarn install

      - name: testing
        run: yarn test

      - name: building
        run: yarn build

      - name: prepare files
        run: |
          mv docs/ /tmp/docs
          cp CNAME /tmp/docs
          touch /tmp/docs/.nojekyll
          rm -fr ./* .github .gitignore .prettierignore .prettierrc
          cp -a /tmp/docs/* ./
          ls -lah

      - name: commit files
        env:
          EMAIL: ${{ secrets.ASDF_EMAIL }}
          NAME: ${{ secrets.ASDF_NAME }}
        run: |
          git status
          git checkout -b master
          git config --local user.email $EMAIL
          git config --local user.name $NAME
          git add .
          git commit -m "new version"
          git log --oneline

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ASDF_PUSH }}
          branch: master
          force: true
